SASTproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('index.urls')),
]

index/urls.py
from django.urls import path

from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('search/', views.search_view, name='search_view'),
    path('search/?keyword=<keyword>', views.search, name='search'),
    path('search/detail/<news_id>', views.detail, name='detail'),
]

index/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    gender_choice = (('boy', 'boy'), ('girl', 'girl'))
    gender = models.CharField(max_length=32, choices=gender_choice, default='boy')

    def __str__(self):
        return self.username


class News(models.Model):
    title = models.CharField(max_length=255)
    source = models.CharField(max_length=255)
    time = models.CharField(max_length=255)
    content = models.CharField(max_length=255)

    def __str__(self):
        return self.title

index/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.db.models import Q
from . models import *
import hashlib


# ENCODE
def hash_code(s, salt='mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


def index(request):
    logged = request.session.get('is_login', None)
    gender = request.session.get('gender', None)
    return render(request, 'index/index.html', {"logged": logged, "gender": gender})


def login(request):
    message = ""
    if request.method == "GET":
        if request.session.get('is_login', None):
            return HttpResponseRedirect(reverse('index:index'))
        else:
            return render(request, 'index/login.html', {"message": message})
    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = User.objects.filter(username=username, password=hash_code(password))
        if user:
            request.session['is_login'] = True
            request.session['gender'] = user[0].gender
            return HttpResponseRedirect(reverse('index:index'))
        else:
            message = "Invalid password !"
            return render(request, 'index/login.html', {"message": message})


def logout(request):
    request.session.flush()
    return HttpResponseRedirect(reverse('index:index'))


def register(request):
    if request.method == "GET":
        return render(request, 'index/register.html', {"message":""})
    else:
        username = request.POST['username']
        user_set = User.objects.filter(username=username)
        if user_set:
            message = "This name already exists."
            return render(request, 'index/register.html', {"message": message})
        else:
            password = request.POST['password']
            password_repeated = request.POST['password_repeated']
            if password != password_repeated:
                message = "The two passwords are not the same! "
                return render(request, 'index/register.html', {"message": message})
            gender = request.POST['gender']
            User.objects.create(username=username, password=hash_code(password), gender=gender)
            return HttpResponseRedirect(reverse('index:login'))


def search_view(request):
    if not request.session.get('is_login', None):
        return HttpResponseRedirect(reverse('index:login'))
    keyword = request.GET['keyword']
    return HttpResponseRedirect(reverse('index:search', args=(keyword,)))


def search(request, keyword):
    gender = request.session.get('gender')
    news_set = News.objects.filter(Q(title__contains=keyword) | Q(content__contains=keyword))
    return render(request, "index/search.html", {"gender": gender, 'news_set': news_set})


def detail(request, news_id):
    gender = request.session.get('gender')
    news = News.objects.get(id=news_id)
    return render(request, "index/detail.html", {"gender": gender, 'news': news})

index/templates/index/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Super Engine</title>
    <link rel="icon" type="image/png" href="../../static/index/images/logo_transparent.png"/>
    <!-- Bootstrap CSS -->
    <link href="../../static/index/styles/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="../../static/index/styles/theme.css" rel="stylesheet" type="text/css">
</head>

<body>
    <main>
    <nav class="navbar navbar-expand navbar-light sticky-top">
        <a class="navbar-brand" href="{% url 'index:index' %}">
            <img src="../../static/index/images/logo_transparent.png" width="40" height="40" alt="" loading="lazy">
        </a>
        <form action="{% url 'index:search_view' %}" method="get">
            <input id="navbar-search-bar" name="keyword" placeholder="Search here: ">
        </form>


        <span id="navbar-user">
            <a id="logout" href="{% url 'index:logout' %}">Log out</a>
            {% if gender == "boy" %}
                <a href="{% url 'index:index' %}">
                    <img id='navbar-user-profile' src="../../static/index/images/boy.png">
                </a>
            {% else %}
                <a href="{% url 'index:index' %}">
                    <img id='navbar-user-profile' src="../../static/index/images/girl.png">
                </a>
            {% endif %}
        </span>
    </nav>
    <div class="news-detail">
        <p class="news-title">
            {{ news.title }}
        </p>
        <p class="news-content">
            {{ news.content }}
        </p>
    </div>
    </main>

    <footer>
        <hr/>
        <p>2020 © Victor | All rights reserved </p>
    </footer>
</body>

</html>

index/templates/index/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Super Engine</title>
    <link rel="icon" type="image/png" href="../../static/index/images/logo_transparent.png"/>
    <!-- Bootstrap CSS -->
    <link href="../../static/index/styles/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="../../static/index/styles/theme.css" rel="stylesheet" type="text/css">
</head>

<body>
    <main>
    <nav class="navbar navbar-expand navbar-light sticky-top">
        <a class="navbar-brand" href="{% url 'index:index' %}">
            <img src="../../static/index/images/logo_transparent.png" width="40" height="40" alt="" loading="lazy">
        </a>

        <span id="navbar-user">
            {% if not logged %}
                <a href="{% url 'index:login' %}">
                    <img id='navbar-user-profile' src="../../static/index/images/logo_transparent.png">
                </a>
            {% else %}
                <a id="logout" href="{% url 'index:logout' %}">Log out</a>
                {% if gender == "boy" %}
                    <a href="{% url 'index:index' %}">
                        <img id='navbar-user-profile' src="../../static/index/images/boy.png">
                    </a>
                {% else %}
                    <a href="{% url 'index:index' %}">
                        <img id='navbar-user-profile' src="../../static/index/images/girl.png">
                    </a>
                {% endif %}
            {% endif %}
        </span>
    </nav>
    <div id="search_area">
        <img src="../../static/index/images/logo_transparent.png">
        <form action="{% url 'index:search_view' %}" method="get">
            <input id="search-bar" name="keyword" placeholder="Welcome to Super Engine ! ">
        </form>
    </div>
    </main>

    <footer>
        <hr/>
        <p>2020 © Victor | All rights reserved </p>
    </footer>
</body>

</html>

index/templates/index/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Super Engine - log in</title>
    <link rel="icon" type="image/png" href="../../static/index/images/logo_transparent.png"/>
    <!-- Bootstrap CSS -->
    <link href="../../static/index/styles/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="../../static/index/styles/theme.css" rel="stylesheet" type="text/css">
</head>

<body>
    <main>
    <nav class="navbar navbar-expand navbar-light sticky-top">
        <a class="navbar-brand" href="{% url 'index:index' %}">
            <img src="../../static/index/images/logo_transparent.png" width="40" height="40" alt="" loading="lazy">
        </a>
    </nav>
    <form id="info-box" style="margin-top: 80px" action="{% url 'index:login' %}" method="post">
        {% csrf_token %}
        <p>Super Engine, just a click</p>
        <input class="userinfo" name="username" placeholder="Name: ">
        <input class="userinfo" type="password" name="password" placeholder="Password: ">
        <div class="info-row">
            <a href="{% url 'index:register' %}">Sign up here</a>
            <input class="submit" type="submit" value="Log in">
        </div>
          {% if message %}
    <div class="alert alert-danger myalert" role="alert">
       {{ message }}
    </div>
    {% endif %}
    </form>
    </main>

    <footer>
        <hr/>
        <p>2020 © Victor | All rights reserved </p>
    </footer>
</body>

</html>

index/templates/index/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Super Engine - register</title>
    <link rel="icon" type="image/png" href="../../static/index/images/logo_transparent.png"/>
    <!-- Bootstrap CSS -->
    <link href="../../static/index/styles/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="../../static/index/styles/theme.css" rel="stylesheet" type="text/css">
</head>

<body>
    <main>
    <nav class="navbar navbar-expand navbar-light sticky-top">
        <a class="navbar-brand" href="{% url 'index:index' %}">
            <img src="../../static/index/images/logo_transparent.png" width="40" height="40" alt="" loading="lazy">
        </a>
    </nav>
    <form id="info-box" style="margin-top: 20px" action="{% url 'index:register' %}" method="post">
        {% csrf_token %}
        <p>Sign up and start using now!</p>
        <input class="userinfo" name="username" placeholder="Name: ">
        <div class="info-row">
            <span>I'm a</span>
            <span><input class="radio" type=radio name="gender" value="boy">boy</span>
            <span><input class="radio" type=radio name="gender" value="girl">girl</span>
        </div>
        <input class="userinfo" type="password" name="password" placeholder="Password: ">
        <input class="userinfo" type="password" name="password_repeated" placeholder="Enter your password again: ">
        <div class="info-row">
            <a href="{% url 'index:login' %}">Log in here </a>
            <input class="submit" type="submit" value="Sign up">
        </div>
        {% if message %}
    <div class="alert alert-danger myalert" role="alert">
       {{ message }}
    </div>
    {% endif %}
    </form>
    </main>

    <footer>
        <hr/>
        <p>2020 © Victor | All rights reserved </p>
    </footer>
</body>

</html>

index/templates/index/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Super Engine</title>
    <link rel="icon" type="image/png" href="../../static/index/images/logo_transparent.png"/>
    <!-- Bootstrap CSS -->
    <link href="../../static/index/styles/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href="../../static/index/styles/theme.css" rel="stylesheet" type="text/css">
</head>

<body>
    <main>
    <nav class="navbar navbar-expand navbar-light sticky-top">
        <a class="navbar-brand" href="{% url 'index:index' %}">
            <img src="../../static/index/images/logo_transparent.png" width="40" height="40" alt="" loading="lazy">
        </a>
        <form action="{% url 'index:search_view' %}" method="get">
            <input id="navbar-search-bar" name="keyword" placeholder="Search here: ">
        </form>

        <span id="navbar-user">
            <a id="logout" href="{% url 'index:logout' %}">Log out</a>
            {% if gender == "boy" %}
                <a href="{% url 'index:index' %}">
                    <img id='navbar-user-profile' src="../../static/index/images/boy.png">
                </a>
            {% else %}
                <a href="{% url 'index:index' %}">
                    <img id='navbar-user-profile' src="../../static/index/images/girl.png">
                </a>
            {% endif %}
        </span>
    </nav>
    {% if news_set %}
        <div id="results-area">
    {% for news in news_set %}
        <div class="news-brief">
            <div class="news-img">
                <img src="../../static/index/images/logo_transparent.png"/>
            </div>
            <div class="news-text">
            <a class="news-title" href="{% url 'index:detail' news.id %}">
                {{ news.title }}
            </a>
            <p class="news-content">
                {{ news.content }}
            </p>
            </div>
        </div>
    {% endfor %}
    {% endif %}
        </div>
    </main>
    <footer>
        <hr/>
        <p>2020 © Victor | All rights reserved </p>
    </footer>
</body>
</html>